---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.serviceTargetPort }}
    protocol: {{ .Values.serviceProtocol }}
  selector:
    app: {{ .Values.appname }}
...